### ISSUE TITLE
Compress more than 2 channels

### ISSUE THREAD

**Issue by alejoe91** [sonos/pyFLAC#12]
Hi,

First of all thank you for the package and the examples!

I'm currently looking for methods to compress data from neural electrophysiology recorded from the brain. We use neural probes with many channels (e.g. 384) and I was wondering if there is a way to tweak the library to allow for more than 2 channels. Is it possible?

Thank you in advance!
Alessio

**Comment by conorsleithsonos** [comment]
@alejoe91 FLAC only natively supports up to 8 channels ([https://xiph.org/flac/faq.html#general__channels](https://xiph.org/flac/faq.html#general__channels)); supporting up to 8 channels could be fairly straightforward, but 384 would require significantly more work. Furthermore, if you want to compress 384 streams in realtime, rather than writing to disk and compressing once the capture is complete, you would need pretty significant CPU resources.

**Comment by alejoe91** [comment]
Thanks for replying @conorsleithsonos 

We are mainly interested in using FLAC offline as it gives quite good results for our data. So CPU resources shouldn't be too much of a concern. Do you know if there are any actions we could take in this regard?

**Comment by joetoddsonos** [comment]
You would first have to make the change in https://github.com/xiph/flac to support up to 384 channels, then we can integrate into this Python wrapper 👍
